---
  sera_inbox_folder_path:
    description: Location for sera inbox folders
    type: string
    required: true
  sera_outbox_folder_path:
    description: Location for sera outbox folders
    type: string
    required: true
  wp1_notification_mail_bioinfo:
    description: email used to notify bioinfo
    type: string
    required: true

  tm_workarea_folder_path:
    description: Location for Twist Myeloid workarea folders
    type: string
    required: true
    default: "stanley"
  tm_outbox_folder_path:
    description: Location for Twist Myeloid outbox folders
    type: string
    required: true
    default: stanley
