---
name: "clean_sera_inbox_outbox"
pack: "ductus_clean"
description: "Rule that triggers cleaning of inbox and outbox data"
enabled: false

trigger:
  type: "core.st2.IntervalTimer"
  parameters:
    unit: "seconds"
    delta: 30

action:
    ref: "ductus_clean.clean_wp1_sera_inbox_outbox"
    parameters:
      project_type: "klinik"
