---
name: "clean_TM_inbox_outbox"
pack: "ductus_clean"
description: "Rule that triggers cleaning of inbox and outbox data for TM"
enabled: false

trigger:
  type: "core.st2.CronTimer"
    parameters:
      timezone: "UTC"
      day_of_week: 2 # or day_of_week: "sun"
      hour: 0
      minute: 0
      second: 0

action:
    ref: "ductus_clean.clean_wp2_TM_inbox_outbox"
